addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.4.6")
addSbtPlugin("com.typesafe.play"         % "sbt-plugin"      % "2.8.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.1.20")
addSbtPlugin("org.wartremover"           % "sbt-wartremover" % "2.4.16")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"    % "0.9.34")
